
spring.application.name=EB-CDC Assistant


# Base de donnees PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/ebcdc_db
spring.datasource.username=ebcdc_user
spring.datasource.password=ebcdc_user
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Serveur

server.port=8080

# AI Engine (Python/FastAPI)
ai.engine.base-url=http://localhost:8000
